-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, bbs.CATEGORY, SUM(bbs.SALES) AS SALES
FROM 
    (
        SELECT b.AUTHOR_ID, b.CATEGORY, b.PRICE * bs.SALES AS SALES
        FROM BOOK b JOIN BOOK_SALES bs ON b.BOOK_ID=bs.BOOK_ID
        WHERE '2022-01-01' <= DATE(SALES_DATE) 
            AND '2022-02-01' > DATE(SALES_DATE)
    ) bbs
    JOIN AUTHOR a ON bbs.AUTHOR_ID=a.AUTHOR_ID
GROUP BY a.AUTHOR_ID, bbs.CATEGORY
ORDER BY a.AUTHOR_ID ASC, bbs.CATEGORY DESC
    
