-- 코드를 입력하세요
SELECT c.CATEGORY, c.MAX_PRICE, fr.PRODUCT_NAME
FROM (
        SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT 
        WHERE CATEGORY in ('과자', '국', '김치', '식용유')
        GROUP BY CATEGORY
    ) c JOIN FOOD_PRODUCT fr ON c.CATEGORY=fr.CATEGORY AND c.MAX_PRICE=fr.PRICE
ORDER BY c.MAX_PRICE DESC

